version: '3'

services:
  db:
    build: docker/mysql
    ports:
      - "3306:3306"
    platform: linux/amd64
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: djandock
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  web:
    build: docker/python
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db