version: '3'

services:
  db:
    build: docker/mysql
    ports:
      - "3306:3306"
    platform: linux/amd64
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: djangodock
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  app:
    build: docker/python
    command: ./wait-for-it.sh db:3306 --timeout=10 --strict -- python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db